// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjTdM0VQT6t-veYz48lNC-Q5DaJ7gliPI',
    appId: '1:547231588820:web:2d00f5b06ad7f5b7d7f641',
    messagingSenderId: '547231588820',
    projectId: 'development-46fea',
    authDomain: 'development-46fea.firebaseapp.com',
    databaseURL: 'https://development-46fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-46fea.firebasestorage.app',
    measurementId: 'G-BB0NNPVY0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSwCT5puFqZOsKy2noHBRsB9pZ0grfWI',
    appId: '1:547231588820:android:dee0b8896fc674a3d7f641',
    messagingSenderId: '547231588820',
    projectId: 'development-46fea',
    databaseURL: 'https://development-46fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-46fea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUnfwX4QV59E4mwRQgiu8FFrFyLRXJxHE',
    appId: '1:547231588820:ios:766411c754ddf4b6d7f641',
    messagingSenderId: '547231588820',
    projectId: 'development-46fea',
    databaseURL: 'https://development-46fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-46fea.firebasestorage.app',
    iosBundleId: 'com.example.ebookJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUnfwX4QV59E4mwRQgiu8FFrFyLRXJxHE',
    appId: '1:547231588820:ios:766411c754ddf4b6d7f641',
    messagingSenderId: '547231588820',
    projectId: 'development-46fea',
    databaseURL: 'https://development-46fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-46fea.firebasestorage.app',
    iosBundleId: 'com.example.ebookJob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjTdM0VQT6t-veYz48lNC-Q5DaJ7gliPI',
    appId: '1:547231588820:web:a2aad00d1c918801d7f641',
    messagingSenderId: '547231588820',
    projectId: 'development-46fea',
    authDomain: 'development-46fea.firebaseapp.com',
    databaseURL: 'https://development-46fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-46fea.firebasestorage.app',
    measurementId: 'G-010J73555F',
  );

}